### ISSUE TITLE
Adjust x-axes for integers to show only whole numbers. (e.g. 2012, 2013, etc., not 2011.5, 2012.0, 2012.5 etc.)

### ISSUE THREAD

**Issue by mjhendrickson** [mjhendrickson/Learning-R#8]
`
ggplot(data = HxMx) +
  geom_bar(mapping = aes(x = year)) +
  scale_y_continuous(name = " ", labels = comma) +
  theme(axis.title.x = element_blank()) +
  labs(title = "Year") 
`
Produces an x axis with decimal places. Change this to whole numbers.
![image](https://user-images.githubusercontent.com/28969821/38316260-4cefadf6-37f8-11e8-9ff0-87b54af525e8.png)

**Comment by mjhendrickson** [comment]
Closing for now as this works and unable to find an automated method.

**Comment by amirhmstu** [comment]
You can use the best ggplot Assist package in rstudio

**Comment by mjhendrickson** [comment]
Thanks @amirhmstu for the pointer. I'm giving it a look, but I'm having issues with it rendering appropriately. I think it may have something to do with my browser extensions. I'll keep playing around with it. Either way, it's a neat tool to help understand how the pieces all come together.
